In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
% matplotlib inline

In [3]:
path = "/Users/prashant/Downloads/Student-Placement-Guidance/Data/Exam Data/2015/CMPN SEM-VI MAY14.xlsx"

In [4]:
sem_6_2015_df = pd.read_excel(path)

In [5]:
sem_6_2015_df

,EXAM SEAT NO.,NAME OF THE CANDIDATE,ACN,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,SPCC,Unnamed: 9,...,SEMR,Unnamed: 33,Unnamed: 34,Unnamed: 35,TOT VI,TOT V,GNT,REMARK,CLASS,Unnamed: 41
NaN,NaN,NaN,TH,NaN,TW,NaN,P&O,NaN,TH,NaN,...,TW,NaN,P&O,NaN,850,850,1700.0,NaN,NaN,NaN
NaN,NaN,Max,100,NaN,25,NaN,50,NaN,100,NaN,...,25,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,Min,40,NaN,10,NaN,20,NaN,40,NaN,...,10,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,146201,ADMANE PRADEEP VIDNYANRAO,41,NaN,20,NaN,44,NaN,60,NaN,...,21,NaN,20,NaN,506,470*+,976.0,PASS,II,Nine Hundred Seventy Six
NaN,146202,AHIRE NAMRATA ASHOK,67,NaN,23,NaN,47,NaN,73,NaN,...,22,NaN,21,NaN,614,534+,1148.0,PASS,I,One Thousand One Hundred Forty Eight
NaN,146203,AMIN RISHITA VIJAYKUMAR,57,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,20,NaN,575,558+,1133.0,PASS,I,One Thousand One Hundred Thirty Three
NaN,146204,AMRE PRITAM ANILKUMAR,59,NaN,23,NaN,47,NaN,70,NaN,...,21,NaN,20,NaN,612,560+,1172.0,PASS,I,One Thousand One Hundred Seventy Two
NaN,146205,ANSAN SUNNY SALAMA,43,NaN,20,NaN,39,NaN,57,NaN,...,22,NaN,21,NaN,542,526x,1068.0,PASS,P,One Thousand Sixty Eight
NaN,146206,ASRANI BHARTI LACHMAN,67,NaN,20,NaN,47,NaN,82,NaN,...,21,NaN,20,NaN,626,545+,1171.0,PASS,I,One Thousand One Hundred Seventy One
NaN,146207,BADE AMIT KERAMBA,51,NaN,21,NaN,42,NaN,56,NaN,...,21,NaN,20,NaN,506*,471+,977.0,PASS,II,Nine Hundred Seventy Seven
NaN,146208,BAGWE KARAN VINAY,73,NaN,22,NaN,47,NaN,84,NaN,...,22,NaN,22,NaN,662,586+,1248.0,PASS,I,One Thousand Two Hundred Forty Eight
NaN,146209,BANDIVADEKAR RUTALI DILIP,70,NaN,23,NaN,47,NaN,80,NaN,...,23,NaN,22,NaN,662,615+,1277.0,PASS,I,One Thousand Two Hundred Seventy Seven
NaN,146210,BARBHAYA RISHI DIVYESH,57,NaN,19,NaN,45,NaN,70,NaN,...,21,NaN,20,NaN,596,562+,1158.0,PASS,I,One Thousand One Hundred Fifty Eight
NaN,146211,BELWALKAR MANALI CHANDRAKANT,46,NaN,22,NaN,43,NaN,67,NaN,...,21,NaN,20,NaN,537*,551+,1088.0,PASS,I,One Thousand Eighty Eight
NaN,146212,BHAGAT DOLLY DEEPAK,40,NaN,24,NaN,48,NaN,51,NaN,...,21,NaN,21,NaN,548,510+,1058.0,PASS,I,One Thousand Fifty Eight
NaN,146213,BHALERAO DEVENDRA SURESH,61,NaN,22,NaN,44,NaN,76,NaN,...,20,NaN,18,NaN,592,531x,1123.0,PASS,P,One Thousand One Hundred Twenty Three
NaN,146214,BORSE KIRAN HILAL,51,NaN,21,NaN,42,NaN,65,NaN,...,20,NaN,18,NaN,538,486+,1024.0,PASS,I,One Thousand Twenty Four
NaN,146215,CHAUHAN ANJALI RAJU,49,NaN,23,NaN,45,NaN,65,NaN,...,22,NaN,20,NaN,540,495*+,1035.0,PASS,I,One Thousand Thirty Five
NaN,146216,CHAVAN GAURAV SHRIDHAR,58,NaN,24,NaN,47,NaN,66,NaN,...,22,NaN,20,NaN,599,532*+,1131.0,PASS,I,One Thousand One Hundred Thirty One
NaN,146217,CHAVAN KOMAL DATTATRAY,50,NaN,20,NaN,43,NaN,54,NaN,...,21,NaN,19,NaN,541,526x,1067.0,PASS,P,One Thousand Sixty Seven
NaN,146218,CHAVAN RAVI BHIKAJI,41,NaN,20,NaN,40,NaN,62,NaN,...,20,NaN,18,NaN,487*,453*+,940.0,PASS,II,NaN
NaN,146219,CHAVAN SHASHANK GAJANAN,55,NaN,23,NaN,45,NaN,77,NaN,...,23,NaN,21,NaN,617,559+,1176.0,PASS,I,NaN
NaN,146220,CHAVHAN AMOL SUBHASH,46,NaN,23,NaN,44,NaN,57,NaN,...,23,NaN,20,NaN,551,491+,1042.0,PASS,I,NaN
NaN,146221,CHILE AKSHAY VISHWANATH,63,NaN,21,NaN,45,NaN,67,NaN,...,22,NaN,19,NaN,609,509+,1118.0,PASS,I,NaN
NaN,146222,CHILKA PRIYANKA RAJENDRA,40,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,19,NaN,545,532*+,1077.0,PASS,I,NaN
NaN,146223,CHONKAR SHRIKAR RAVINDRA,46,NaN,23,NaN,44,NaN,59,NaN,...,21,NaN,21,NaN,549,538+,1087.0,PASS,I,NaN
NaN,146224,DALVI NILESHA NANDKISHOR,47,NaN,19,NaN,47,NaN,68,NaN,...,23,NaN,22,NaN,576,517+,1093.0,PASS,I,NaN
NaN,146225,DANDE AKASH NARAYAN,65,NaN,23,NaN,47,NaN,72,NaN,...,23,NaN,18,NaN,624,585+,1209.0,PASS,I,NaN
NaN,146226,DAVE RAJENDRA AJAY,60,NaN,23,NaN,46,NaN,72,NaN,...,21,NaN,19,NaN,626,580+,1206.0,PASS,I,NaN
NaN,146227,DEORE SANKET GOVIND,41,NaN,20,NaN,39,NaN,44,NaN,...,20,NaN,19,NaN,480,480x,960.0,PASS,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,146332,SOMAIYA JAINIM DILIP,58,NaN,20,NaN,41,NaN,59,NaN,...,19,NaN,19,NaN,558,546x,1104.0,PASS,P,NaN
NaN,146333,SONI RAINIK OMPRAKASH,15,F,21,E,42,E,51,E,...,21,E,21,E,507,519x,1026.0,FAIL,--,NaN
NaN,146334,SRIKANTH RAVEE,57,NaN,23,NaN,43,NaN,55,NaN,...,22,NaN,22,NaN,592,548x,1140.0,PASS,P,NaN
NaN,146335,SUMAN SIDDAHARTH SURESH,42,NaN,21,NaN,45,NaN,52,NaN,...,21,NaN,22,NaN,549,512x,1061.0,PASS,P,NaN
NaN,146336,SURVE NEHA VILAS,69,NaN,22,NaN,42,NaN,77,NaN,...,21,NaN,22,NaN,635,527+,1162.0,PASS,I,NaN
NaN,146337,SURYAWANSHI PRIYANKA MADHUKAR,44,NaN,23,NaN,45,NaN,51,NaN,...,21,NaN,22,NaN,539,520x,1059.0,PASS,P,NaN
NaN,146338,TANDEL LINA LAXMAN,49,NaN,23,NaN,45,NaN,67,NaN,...,22,NaN,23,NaN,603,517+,1120.0,PASS,I,NaN
NaN,146339,THAPLIYAL AJAY SHIVSHARAN,49,NaN,21,NaN,38,NaN,50,NaN,...,20,NaN,21,NaN,518,468+,986.0,PASS,II,NaN
NaN,146340,UBALE SANCHI SANDEEP,54,NaN,20,NaN,40,NaN,50,NaN,...,22,NaN,23,NaN,529,458+,987.0,PASS,II,NaN
NaN,146341,UPADHYAY PRASHANT VIJAY,57,NaN,21,NaN,39,NaN,55,NaN,...,19,NaN,20,NaN,545,513x,1058.0,PASS,P,NaN
NaN,146342,VARSHINI RAMARAJ,65,NaN,24,NaN,48,NaN,70,NaN,...,22,NaN,23,NaN,645,601+,1246.0,PASS,I,NaN
NaN,146343,VYAS SAGAR MAHENDRA,65,NaN,21,NaN,42,NaN,57,NaN,...,22,NaN,20,NaN,579,522+,1101.0,PASS,I,NaN
NaN,146344,WALINJKAR KRITIKA BHUSHAN,70,NaN,24,NaN,46,NaN,69,NaN,...,22,NaN,20,NaN,644,559+,1203.0,PASS,I,NaN
NaN,146345,ZEPLE PRIYANKA KESHAV,40,NaN,23,NaN,46,NaN,53,NaN,...,22,NaN,20,NaN,581,527+,1108.0,PASS,I,NaN
NaN,146346,GALANDE BHUSHAN RAMESH,45,E,20,E,42,E,AB,NaN,...,18,E,19,E,376,0,376.0,FAIL,--,NaN
NaN,146347,PARDHIYE PRATHMESH VIJAY,57,NaN,19,NaN,38,NaN,50,NaN,...,22,NaN,20,NaN,554,502x,1056.0,PASS,P,NaN
NaN,146348,WANI TEJAS VILAS,40,NaN,20,NaN,42,NaN,51,NaN,...,20,NaN,18,NaN,491,471x,962.0,PASS,P,NaN
NaN,146349,SHAH ZALAK NIPUL,41,NaN,20,NaN,34,NaN,45,NaN,...,20,NaN,18,NaN,501,463+,964.0,PASS,II,NaN
NaN,146350,SALVI SANDESH DILIP,29,F,21,E,38,E,40,E,...,20,E,18,E,448,0,448.0,FAIL,--,NaN
NaN,146351,BHOITE KISHORI PRABHAR,40,NaN,20,NaN,40,NaN,40,NaN,...,21,NaN,19,NaN,486,476x,962.0,PASS,P,NaN
NaN,146352,BAJETHA GAURAV SINGH GOVIND,40,E,19,E,41,E,49,E,...,20,E,21,E,456,493x,949.0,FAIL,--,NaN
NaN,146353,SHINDE PRATIKSHA DNYANESHWAR,63,NaN,22,NaN,44,NaN,59,NaN,...,21,NaN,22,NaN,583,490+,1073.0,PASS,I,NaN
NaN,146354,AMBRE ABHISHEK AURN,AB,NaN,23+,,38+,,AB,NaN,...,23+,,23+,,382,0,382.0,ABSENT,AB,NaN
NaN,146355,BHOLE NILIMA SURESH,AB,NaN,19+,,41+,,AB,NaN,...,21+,,21+,,277,0,277.0,ABSENT,AB,NaN
NaN,146356,CHOUDHARY SHANKAR MAFATLAL,40+,,23+,,46+,,45+,,...,23+,,23+,,537,520x,1057.0,PASS,P,NaN
NaN,146357,DEVARKAR SANKALP HEMANT,40+,,14+,,35+,,AB,NaN,...,18+,,18+,,362,0,362.0,ABSENT,AB,NaN
NaN,146358,DHOTRE KUNAL RAMCHANDRA,44,NaN,19+,,38+,,44+,,...,20+,,21+,,487,464x,951.0,PASS,P,NaN
NaN,146359,GHUMAN RAJNEET SINGH IQBAL SINGH,AB,NaN,20+,,44+,,AB,NaN,...,20+,,20+,,253,0,253.0,ABSENT,AB,NaN
NaN,PC4201,CHITRE ABHISHEK ANIL,5,F,21,E,40,E,40,E,...,18,E,19,E,371,0,371.0,FAIL,--,NaN
NaN,PC4202,PALEKAR AKSHAY ANIL,34,F,21,E,40,E,40,E,...,18,E,19,E,422,0,422.0,FAIL,--,NaN

In [6]:
sem_6_2015_df.dropna(subset=['EXAM SEAT NO.'],inplace=True)

In [7]:
sem_6_2015_df.dropna(axis=0, how='all',inplace=True)

In [8]:
sem_6_2015_df.index = sem_6_2015_df['EXAM SEAT NO.']

In [9]:
sem_6_2015_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 161 entries, 146201 to PC4202
Data columns (total 42 columns):
EXAM SEAT NO.            161 non-null object
NAME OF THE CANDIDATE    161 non-null object
ACN                      161 non-null object
Unnamed: 3               15 non-null object
Unnamed: 4               161 non-null object
Unnamed: 5               19 non-null object
Unnamed: 6               161 non-null object
Unnamed: 7               19 non-null object
SPCC                     161 non-null object
Unnamed: 9               14 non-null object
Unnamed: 10              161 non-null object
Unnamed: 11              19 non-null object
Unnamed: 12              161 non-null object
Unnamed: 13              19 non-null object
OOSE                     161 non-null object
Unnamed: 15              15 non-null object
Unnamed: 16              161 non-null object
Unnamed: 17              19 non-null object
Unnamed: 18              161 non-null object
Unnamed: 19              19 non-null object
AMP                      161 non-null object
Unnamed: 21              12 non-null object
Unnamed: 22              161 non-null object
Unnamed: 23              19 non-null object
Unnamed: 24              161 non-null object
Unnamed: 25              19 non-null object
DWM                      161 non-null object
Unnamed: 27              16 non-null object
Unnamed: 28              161 non-null object
Unnamed: 29              19 non-null object
Unnamed: 30              161 non-null object
Unnamed: 31              19 non-null object
SEMR                     161 non-null object
Unnamed: 33              19 non-null object
Unnamed: 34              161 non-null object
Unnamed: 35              19 non-null object
TOT VI                   161 non-null object
TOT V                    161 non-null object
GNT                      161 non-null float64
REMARK                   161 non-null object
CLASS                    161 non-null object
Unnamed: 41              17 non-null object
dtypes: float64(1), object(41)
memory usage: 54.1+ KB

In [10]:
sem_6_2015_df.columns.values[[3,4,5,6,7]] = ['ACN_Grade','ACN_TW','ACN_TW_Grade','ACN_P&O','ACN_P&O_Grade']
sem_6_2015_df.columns.values[[9,10,11,12,13]] = ['SPCC_Grade','SPCC_TW','SPCC_TW_Grade','SPCC_P&O','SPCC_P&O_Grade']
sem_6_2015_df.columns.values[[15,16,17,18,19]] = ['OOSE_Grade','OOSE_TW','OOSE_TW_Grade','OOSE_P&O','OOSE_P&O_Grade']
sem_6_2015_df.columns.values[[21,22,23,24,25]] = ['AMP_Grade','AMP_TW','AMP_TW_Grade','AMP_P&O','AMP_P&O_Grade']
sem_6_2015_df.columns.values[[27,28,29,30,31]] = ['DWM_Grade','DWM_TW','DWM_TW_Grade','DWM_P&O','DWM_P&O_Grade']
sem_6_2015_df.columns.values[[33,34,35]] = ['SEMR_Grade','SEMR_P&O','SEMR_P&O_Grade']

In [13]:
sem_6_2015_df = sem_6_2015_df.rename_axis(lambda x: x, 1, True)

/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using 'rename_axis' to alter labels is deprecated. Use '.rename' instead
  """Entry point for launching an IPython kernel.

In [14]:
sem_6_2015_df

,EXAM SEAT NO.,NAME OF THE CANDIDATE,ACN,ACN_Grade,ACN_TW,ACN_TW_Grade,ACN_P&O,ACN_P&O_Grade,SPCC,SPCC_Grade,...,SEMR,SEMR_Grade,SEMR_P&O,SEMR_P&O_Grade,TOT VI,TOT V,GNT,REMARK,CLASS,Unnamed: 41
EXAM SEAT NO.,,,,,,,,,,,,,,,,,,,,,
146201,146201,ADMANE PRADEEP VIDNYANRAO,41,NaN,20,NaN,44,NaN,60,NaN,...,21,NaN,20,NaN,506,470*+,976.0,PASS,II,Nine Hundred Seventy Six
146202,146202,AHIRE NAMRATA ASHOK,67,NaN,23,NaN,47,NaN,73,NaN,...,22,NaN,21,NaN,614,534+,1148.0,PASS,I,One Thousand One Hundred Forty Eight
146203,146203,AMIN RISHITA VIJAYKUMAR,57,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,20,NaN,575,558+,1133.0,PASS,I,One Thousand One Hundred Thirty Three
146204,146204,AMRE PRITAM ANILKUMAR,59,NaN,23,NaN,47,NaN,70,NaN,...,21,NaN,20,NaN,612,560+,1172.0,PASS,I,One Thousand One Hundred Seventy Two
146205,146205,ANSAN SUNNY SALAMA,43,NaN,20,NaN,39,NaN,57,NaN,...,22,NaN,21,NaN,542,526x,1068.0,PASS,P,One Thousand Sixty Eight
146206,146206,ASRANI BHARTI LACHMAN,67,NaN,20,NaN,47,NaN,82,NaN,...,21,NaN,20,NaN,626,545+,1171.0,PASS,I,One Thousand One Hundred Seventy One
146207,146207,BADE AMIT KERAMBA,51,NaN,21,NaN,42,NaN,56,NaN,...,21,NaN,20,NaN,506*,471+,977.0,PASS,II,Nine Hundred Seventy Seven
146208,146208,BAGWE KARAN VINAY,73,NaN,22,NaN,47,NaN,84,NaN,...,22,NaN,22,NaN,662,586+,1248.0,PASS,I,One Thousand Two Hundred Forty Eight
146209,146209,BANDIVADEKAR RUTALI DILIP,70,NaN,23,NaN,47,NaN,80,NaN,...,23,NaN,22,NaN,662,615+,1277.0,PASS,I,One Thousand Two Hundred Seventy Seven
146210,146210,BARBHAYA RISHI DIVYESH,57,NaN,19,NaN,45,NaN,70,NaN,...,21,NaN,20,NaN,596,562+,1158.0,PASS,I,One Thousand One Hundred Fifty Eight
146211,146211,BELWALKAR MANALI CHANDRAKANT,46,NaN,22,NaN,43,NaN,67,NaN,...,21,NaN,20,NaN,537*,551+,1088.0,PASS,I,One Thousand Eighty Eight
146212,146212,BHAGAT DOLLY DEEPAK,40,NaN,24,NaN,48,NaN,51,NaN,...,21,NaN,21,NaN,548,510+,1058.0,PASS,I,One Thousand Fifty Eight
146213,146213,BHALERAO DEVENDRA SURESH,61,NaN,22,NaN,44,NaN,76,NaN,...,20,NaN,18,NaN,592,531x,1123.0,PASS,P,One Thousand One Hundred Twenty Three
146214,146214,BORSE KIRAN HILAL,51,NaN,21,NaN,42,NaN,65,NaN,...,20,NaN,18,NaN,538,486+,1024.0,PASS,I,One Thousand Twenty Four
146215,146215,CHAUHAN ANJALI RAJU,49,NaN,23,NaN,45,NaN,65,NaN,...,22,NaN,20,NaN,540,495*+,1035.0,PASS,I,One Thousand Thirty Five
146216,146216,CHAVAN GAURAV SHRIDHAR,58,NaN,24,NaN,47,NaN,66,NaN,...,22,NaN,20,NaN,599,532*+,1131.0,PASS,I,One Thousand One Hundred Thirty One
146217,146217,CHAVAN KOMAL DATTATRAY,50,NaN,20,NaN,43,NaN,54,NaN,...,21,NaN,19,NaN,541,526x,1067.0,PASS,P,One Thousand Sixty Seven
146218,146218,CHAVAN RAVI BHIKAJI,41,NaN,20,NaN,40,NaN,62,NaN,...,20,NaN,18,NaN,487*,453*+,940.0,PASS,II,NaN
146219,146219,CHAVAN SHASHANK GAJANAN,55,NaN,23,NaN,45,NaN,77,NaN,...,23,NaN,21,NaN,617,559+,1176.0,PASS,I,NaN
146220,146220,CHAVHAN AMOL SUBHASH,46,NaN,23,NaN,44,NaN,57,NaN,...,23,NaN,20,NaN,551,491+,1042.0,PASS,I,NaN
146221,146221,CHILE AKSHAY VISHWANATH,63,NaN,21,NaN,45,NaN,67,NaN,...,22,NaN,19,NaN,609,509+,1118.0,PASS,I,NaN
146222,146222,CHILKA PRIYANKA RAJENDRA,40,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,19,NaN,545,532*+,1077.0,PASS,I,NaN
146223,146223,CHONKAR SHRIKAR RAVINDRA,46,NaN,23,NaN,44,NaN,59,NaN,...,21,NaN,21,NaN,549,538+,1087.0,PASS,I,NaN
146224,146224,DALVI NILESHA NANDKISHOR,47,NaN,19,NaN,47,NaN,68,NaN,...,23,NaN,22,NaN,576,517+,1093.0,PASS,I,NaN
146225,146225,DANDE AKASH NARAYAN,65,NaN,23,NaN,47,NaN,72,NaN,...,23,NaN,18,NaN,624,585+,1209.0,PASS,I,NaN
146226,146226,DAVE RAJENDRA AJAY,60,NaN,23,NaN,46,NaN,72,NaN,...,21,NaN,19,NaN,626,580+,1206.0,PASS,I,NaN
146227,146227,DEORE SANKET GOVIND,41,NaN,20,NaN,39,NaN,44,NaN,...,20,NaN,19,NaN,480,480x,960.0,PASS,P,NaN
146228,146228,DESAI CHINMAY PRAKASH,49,NaN,19,NaN,38,NaN,65,NaN,...,18,NaN,20,NaN,509*,0,509.0,PASS,RS 5,NaN
146229,146229,DEVLEKAR RAHUL PRAKASH,54,NaN,21,NaN,43,NaN,54,NaN,...,21,NaN,20,NaN,571,519+,1090.0,PASS,I,NaN
146230,146230,DHULE AMEY YASHWANT,67,NaN,22,NaN,46,NaN,79,NaN,...,21,NaN,22,NaN,635,525+,1160.0,PASS,I,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146332,146332,SOMAIYA JAINIM DILIP,58,NaN,20,NaN,41,NaN,59,NaN,...,19,NaN,19,NaN,558,546x,1104.0,PASS,P,NaN
146333,146333,SONI RAINIK OMPRAKASH,15,F,21,E,42,E,51,E,...,21,E,21,E,507,519x,1026.0,FAIL,--,NaN
146334,146334,SRIKANTH RAVEE,57,NaN,23,NaN,43,NaN,55,NaN,...,22,NaN,22,NaN,592,548x,1140.0,PASS,P,NaN
146335,146335,SUMAN SIDDAHARTH SURESH,42,NaN,21,NaN,45,NaN,52,NaN,...,21,NaN,22,NaN,549,512x,1061.0,PASS,P,NaN
146336,146336,SURVE NEHA VILAS,69,NaN,22,NaN,42,NaN,77,NaN,...,21,NaN,22,NaN,635,527+,1162.0,PASS,I,NaN
146337,146337,SURYAWANSHI PRIYANKA MADHUKAR,44,NaN,23,NaN,45,NaN,51,NaN,...,21,NaN,22,NaN,539,520x,1059.0,PASS,P,NaN
146338,146338,TANDEL LINA LAXMAN,49,NaN,23,NaN,45,NaN,67,NaN,...,22,NaN,23,NaN,603,517+,1120.0,PASS,I,NaN
146339,146339,THAPLIYAL AJAY SHIVSHARAN,49,NaN,21,NaN,38,NaN,50,NaN,...,20,NaN,21,NaN,518,468+,986.0,PASS,II,NaN
146340,146340,UBALE SANCHI SANDEEP,54,NaN,20,NaN,40,NaN,50,NaN,...,22,NaN,23,NaN,529,458+,987.0,PASS,II,NaN
146341,146341,UPADHYAY PRASHANT VIJAY,57,NaN,21,NaN,39,NaN,55,NaN,...,19,NaN,20,NaN,545,513x,1058.0,PASS,P,NaN
146342,146342,VARSHINI RAMARAJ,65,NaN,24,NaN,48,NaN,70,NaN,...,22,NaN,23,NaN,645,601+,1246.0,PASS,I,NaN
146343,146343,VYAS SAGAR MAHENDRA,65,NaN,21,NaN,42,NaN,57,NaN,...,22,NaN,20,NaN,579,522+,1101.0,PASS,I,NaN
146344,146344,WALINJKAR KRITIKA BHUSHAN,70,NaN,24,NaN,46,NaN,69,NaN,...,22,NaN,20,NaN,644,559+,1203.0,PASS,I,NaN
146345,146345,ZEPLE PRIYANKA KESHAV,40,NaN,23,NaN,46,NaN,53,NaN,...,22,NaN,20,NaN,581,527+,1108.0,PASS,I,NaN
146346,146346,GALANDE BHUSHAN RAMESH,45,E,20,E,42,E,AB,NaN,...,18,E,19,E,376,0,376.0,FAIL,--,NaN
146347,146347,PARDHIYE PRATHMESH VIJAY,57,NaN,19,NaN,38,NaN,50,NaN,...,22,NaN,20,NaN,554,502x,1056.0,PASS,P,NaN
146348,146348,WANI TEJAS VILAS,40,NaN,20,NaN,42,NaN,51,NaN,...,20,NaN,18,NaN,491,471x,962.0,PASS,P,NaN
146349,146349,SHAH ZALAK NIPUL,41,NaN,20,NaN,34,NaN,45,NaN,...,20,NaN,18,NaN,501,463+,964.0,PASS,II,NaN
146350,146350,SALVI SANDESH DILIP,29,F,21,E,38,E,40,E,...,20,E,18,E,448,0,448.0,FAIL,--,NaN
146351,146351,BHOITE KISHORI PRABHAR,40,NaN,20,NaN,40,NaN,40,NaN,...,21,NaN,19,NaN,486,476x,962.0,PASS,P,NaN
146352,146352,BAJETHA GAURAV SINGH GOVIND,40,E,19,E,41,E,49,E,...,20,E,21,E,456,493x,949.0,FAIL,--,NaN
146353,146353,SHINDE PRATIKSHA DNYANESHWAR,63,NaN,22,NaN,44,NaN,59,NaN,...,21,NaN,22,NaN,583,490+,1073.0,PASS,I,NaN
146354,146354,AMBRE ABHISHEK AURN,AB,NaN,23+,,38+,,AB,NaN,...,23+,,23+,,382,0,382.0,ABSENT,AB,NaN
146355,146355,BHOLE NILIMA SURESH,AB,NaN,19+,,41+,,AB,NaN,...,21+,,21+,,277,0,277.0,ABSENT,AB,NaN
146356,146356,CHOUDHARY SHANKAR MAFATLAL,40+,,23+,,46+,,45+,,...,23+,,23+,,537,520x,1057.0,PASS,P,NaN
146357,146357,DEVARKAR SANKALP HEMANT,40+,,14+,,35+,,AB,NaN,...,18+,,18+,,362,0,362.0,ABSENT,AB,NaN
146358,146358,DHOTRE KUNAL RAMCHANDRA,44,NaN,19+,,38+,,44+,,...,20+,,21+,,487,464x,951.0,PASS,P,NaN
146359,146359,GHUMAN RAJNEET SINGH IQBAL SINGH,AB,NaN,20+,,44+,,AB,NaN,...,20+,,20+,,253,0,253.0,ABSENT,AB,NaN
PC4201,PC4201,CHITRE ABHISHEK ANIL,5,F,21,E,40,E,40,E,...,18,E,19,E,371,0,371.0,FAIL,--,NaN
PC4202,PC4202,PALEKAR AKSHAY ANIL,34,F,21,E,40,E,40,E,...,18,E,19,E,422,0,422.0,FAIL,--,NaN

In [15]:
sem_6_2015_df['ACN'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['ACN_TW'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['ACN_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['SPCC'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['SPCC_TW'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['SPCC_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['OOSE'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['OOSE_TW'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['OOSE_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['AMP'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['AMP_TW'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['AMP_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['DWM'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['DWM_TW'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['DWM_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['SEMR'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['SEMR_P&O'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

sem_6_2015_df['TOT VI'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['TOT V'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
sem_6_2015_df['GNT'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

#removes non digit characters from pandas column AMIV
sem_6_2015_df

,EXAM SEAT NO.,NAME OF THE CANDIDATE,ACN,ACN_Grade,ACN_TW,ACN_TW_Grade,ACN_P&O,ACN_P&O_Grade,SPCC,SPCC_Grade,...,SEMR,SEMR_Grade,SEMR_P&O,SEMR_P&O_Grade,TOT VI,TOT V,GNT,REMARK,CLASS,Unnamed: 41
EXAM SEAT NO.,,,,,,,,,,,,,,,,,,,,,
146201,146201,ADMANE PRADEEP VIDNYANRAO,41,NaN,20,NaN,44,NaN,60,NaN,...,21,NaN,20,NaN,506,470,976.0,PASS,II,Nine Hundred Seventy Six
146202,146202,AHIRE NAMRATA ASHOK,67,NaN,23,NaN,47,NaN,73,NaN,...,22,NaN,21,NaN,614,534,1148.0,PASS,I,One Thousand One Hundred Forty Eight
146203,146203,AMIN RISHITA VIJAYKUMAR,57,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,20,NaN,575,558,1133.0,PASS,I,One Thousand One Hundred Thirty Three
146204,146204,AMRE PRITAM ANILKUMAR,59,NaN,23,NaN,47,NaN,70,NaN,...,21,NaN,20,NaN,612,560,1172.0,PASS,I,One Thousand One Hundred Seventy Two
146205,146205,ANSAN SUNNY SALAMA,43,NaN,20,NaN,39,NaN,57,NaN,...,22,NaN,21,NaN,542,526,1068.0,PASS,P,One Thousand Sixty Eight
146206,146206,ASRANI BHARTI LACHMAN,67,NaN,20,NaN,47,NaN,82,NaN,...,21,NaN,20,NaN,626,545,1171.0,PASS,I,One Thousand One Hundred Seventy One
146207,146207,BADE AMIT KERAMBA,51,NaN,21,NaN,42,NaN,56,NaN,...,21,NaN,20,NaN,506,471,977.0,PASS,II,Nine Hundred Seventy Seven
146208,146208,BAGWE KARAN VINAY,73,NaN,22,NaN,47,NaN,84,NaN,...,22,NaN,22,NaN,662,586,1248.0,PASS,I,One Thousand Two Hundred Forty Eight
146209,146209,BANDIVADEKAR RUTALI DILIP,70,NaN,23,NaN,47,NaN,80,NaN,...,23,NaN,22,NaN,662,615,1277.0,PASS,I,One Thousand Two Hundred Seventy Seven
146210,146210,BARBHAYA RISHI DIVYESH,57,NaN,19,NaN,45,NaN,70,NaN,...,21,NaN,20,NaN,596,562,1158.0,PASS,I,One Thousand One Hundred Fifty Eight
146211,146211,BELWALKAR MANALI CHANDRAKANT,46,NaN,22,NaN,43,NaN,67,NaN,...,21,NaN,20,NaN,537,551,1088.0,PASS,I,One Thousand Eighty Eight
146212,146212,BHAGAT DOLLY DEEPAK,40,NaN,24,NaN,48,NaN,51,NaN,...,21,NaN,21,NaN,548,510,1058.0,PASS,I,One Thousand Fifty Eight
146213,146213,BHALERAO DEVENDRA SURESH,61,NaN,22,NaN,44,NaN,76,NaN,...,20,NaN,18,NaN,592,531,1123.0,PASS,P,One Thousand One Hundred Twenty Three
146214,146214,BORSE KIRAN HILAL,51,NaN,21,NaN,42,NaN,65,NaN,...,20,NaN,18,NaN,538,486,1024.0,PASS,I,One Thousand Twenty Four
146215,146215,CHAUHAN ANJALI RAJU,49,NaN,23,NaN,45,NaN,65,NaN,...,22,NaN,20,NaN,540,495,1035.0,PASS,I,One Thousand Thirty Five
146216,146216,CHAVAN GAURAV SHRIDHAR,58,NaN,24,NaN,47,NaN,66,NaN,...,22,NaN,20,NaN,599,532,1131.0,PASS,I,One Thousand One Hundred Thirty One
146217,146217,CHAVAN KOMAL DATTATRAY,50,NaN,20,NaN,43,NaN,54,NaN,...,21,NaN,19,NaN,541,526,1067.0,PASS,P,One Thousand Sixty Seven
146218,146218,CHAVAN RAVI BHIKAJI,41,NaN,20,NaN,40,NaN,62,NaN,...,20,NaN,18,NaN,487,453,940.0,PASS,II,NaN
146219,146219,CHAVAN SHASHANK GAJANAN,55,NaN,23,NaN,45,NaN,77,NaN,...,23,NaN,21,NaN,617,559,1176.0,PASS,I,NaN
146220,146220,CHAVHAN AMOL SUBHASH,46,NaN,23,NaN,44,NaN,57,NaN,...,23,NaN,20,NaN,551,491,1042.0,PASS,I,NaN
146221,146221,CHILE AKSHAY VISHWANATH,63,NaN,21,NaN,45,NaN,67,NaN,...,22,NaN,19,NaN,609,509,1118.0,PASS,I,NaN
146222,146222,CHILKA PRIYANKA RAJENDRA,40,NaN,22,NaN,46,NaN,66,NaN,...,21,NaN,19,NaN,545,532,1077.0,PASS,I,NaN
146223,146223,CHONKAR SHRIKAR RAVINDRA,46,NaN,23,NaN,44,NaN,59,NaN,...,21,NaN,21,NaN,549,538,1087.0,PASS,I,NaN
146224,146224,DALVI NILESHA NANDKISHOR,47,NaN,19,NaN,47,NaN,68,NaN,...,23,NaN,22,NaN,576,517,1093.0,PASS,I,NaN
146225,146225,DANDE AKASH NARAYAN,65,NaN,23,NaN,47,NaN,72,NaN,...,23,NaN,18,NaN,624,585,1209.0,PASS,I,NaN
146226,146226,DAVE RAJENDRA AJAY,60,NaN,23,NaN,46,NaN,72,NaN,...,21,NaN,19,NaN,626,580,1206.0,PASS,I,NaN
146227,146227,DEORE SANKET GOVIND,41,NaN,20,NaN,39,NaN,44,NaN,...,20,NaN,19,NaN,480,480,960.0,PASS,P,NaN
146228,146228,DESAI CHINMAY PRAKASH,49,NaN,19,NaN,38,NaN,65,NaN,...,18,NaN,20,NaN,509,0,509.0,PASS,RS 5,NaN
146229,146229,DEVLEKAR RAHUL PRAKASH,54,NaN,21,NaN,43,NaN,54,NaN,...,21,NaN,20,NaN,571,519,1090.0,PASS,I,NaN
146230,146230,DHULE AMEY YASHWANT,67,NaN,22,NaN,46,NaN,79,NaN,...,21,NaN,22,NaN,635,525,1160.0,PASS,I,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146332,146332,SOMAIYA JAINIM DILIP,58,NaN,20,NaN,41,NaN,59,NaN,...,19,NaN,19,NaN,558,546,1104.0,PASS,P,NaN
146333,146333,SONI RAINIK OMPRAKASH,15,F,21,E,42,E,51,E,...,21,E,21,E,507,519,1026.0,FAIL,--,NaN
146334,146334,SRIKANTH RAVEE,57,NaN,23,NaN,43,NaN,55,NaN,...,22,NaN,22,NaN,592,548,1140.0,PASS,P,NaN
146335,146335,SUMAN SIDDAHARTH SURESH,42,NaN,21,NaN,45,NaN,52,NaN,...,21,NaN,22,NaN,549,512,1061.0,PASS,P,NaN
146336,146336,SURVE NEHA VILAS,69,NaN,22,NaN,42,NaN,77,NaN,...,21,NaN,22,NaN,635,527,1162.0,PASS,I,NaN
146337,146337,SURYAWANSHI PRIYANKA MADHUKAR,44,NaN,23,NaN,45,NaN,51,NaN,...,21,NaN,22,NaN,539,520,1059.0,PASS,P,NaN
146338,146338,TANDEL LINA LAXMAN,49,NaN,23,NaN,45,NaN,67,NaN,...,22,NaN,23,NaN,603,517,1120.0,PASS,I,NaN
146339,146339,THAPLIYAL AJAY SHIVSHARAN,49,NaN,21,NaN,38,NaN,50,NaN,...,20,NaN,21,NaN,518,468,986.0,PASS,II,NaN
146340,146340,UBALE SANCHI SANDEEP,54,NaN,20,NaN,40,NaN,50,NaN,...,22,NaN,23,NaN,529,458,987.0,PASS,II,NaN
146341,146341,UPADHYAY PRASHANT VIJAY,57,NaN,21,NaN,39,NaN,55,NaN,...,19,NaN,20,NaN,545,513,1058.0,PASS,P,NaN
146342,146342,VARSHINI RAMARAJ,65,NaN,24,NaN,48,NaN,70,NaN,...,22,NaN,23,NaN,645,601,1246.0,PASS,I,NaN
146343,146343,VYAS SAGAR MAHENDRA,65,NaN,21,NaN,42,NaN,57,NaN,...,22,NaN,20,NaN,579,522,1101.0,PASS,I,NaN
146344,146344,WALINJKAR KRITIKA BHUSHAN,70,NaN,24,NaN,46,NaN,69,NaN,...,22,NaN,20,NaN,644,559,1203.0,PASS,I,NaN
146345,146345,ZEPLE PRIYANKA KESHAV,40,NaN,23,NaN,46,NaN,53,NaN,...,22,NaN,20,NaN,581,527,1108.0,PASS,I,NaN
146346,146346,GALANDE BHUSHAN RAMESH,45,E,20,E,42,E,,NaN,...,18,E,19,E,376,0,376.0,FAIL,--,NaN
146347,146347,PARDHIYE PRATHMESH VIJAY,57,NaN,19,NaN,38,NaN,50,NaN,...,22,NaN,20,NaN,554,502,1056.0,PASS,P,NaN
146348,146348,WANI TEJAS VILAS,40,NaN,20,NaN,42,NaN,51,NaN,...,20,NaN,18,NaN,491,471,962.0,PASS,P,NaN
146349,146349,SHAH ZALAK NIPUL,41,NaN,20,NaN,34,NaN,45,NaN,...,20,NaN,18,NaN,501,463,964.0,PASS,II,NaN
146350,146350,SALVI SANDESH DILIP,29,F,21,E,38,E,40,E,...,20,E,18,E,448,0,448.0,FAIL,--,NaN
146351,146351,BHOITE KISHORI PRABHAR,40,NaN,20,NaN,40,NaN,40,NaN,...,21,NaN,19,NaN,486,476,962.0,PASS,P,NaN
146352,146352,BAJETHA GAURAV SINGH GOVIND,40,E,19,E,41,E,49,E,...,20,E,21,E,456,493,949.0,FAIL,--,NaN
146353,146353,SHINDE PRATIKSHA DNYANESHWAR,63,NaN,22,NaN,44,NaN,59,NaN,...,21,NaN,22,NaN,583,490,1073.0,PASS,I,NaN
146354,146354,AMBRE ABHISHEK AURN,,NaN,23,,38,,,NaN,...,23,,23,,382,0,382.0,ABSENT,AB,NaN
146355,146355,BHOLE NILIMA SURESH,,NaN,19,,41,,,NaN,...,21,,21,,277,0,277.0,ABSENT,AB,NaN
146356,146356,CHOUDHARY SHANKAR MAFATLAL,40,,23,,46,,45,,...,23,,23,,537,520,1057.0,PASS,P,NaN
146357,146357,DEVARKAR SANKALP HEMANT,40,,14,,35,,,NaN,...,18,,18,,362,0,362.0,ABSENT,AB,NaN
146358,146358,DHOTRE KUNAL RAMCHANDRA,44,NaN,19,,38,,44,,...,20,,21,,487,464,951.0,PASS,P,NaN
146359,146359,GHUMAN RAJNEET SINGH IQBAL SINGH,,NaN,20,,44,,,NaN,...,20,,20,,253,0,253.0,ABSENT,AB,NaN
PC4201,PC4201,CHITRE ABHISHEK ANIL,5,F,21,E,40,E,40,E,...,18,E,19,E,371,0,371.0,FAIL,--,NaN
PC4202,PC4202,PALEKAR AKSHAY ANIL,34,F,21,E,40,E,40,E,...,18,E,19,E,422,0,422.0,FAIL,--,NaN

In [16]:
sem_6_2015_df['ACN'] = pd.to_numeric(sem_6_2015_df["ACN"], errors='coerce')
sem_6_2015_df['ACN_TW'] = pd.to_numeric(sem_6_2015_df["ACN_TW"], errors='coerce')
sem_6_2015_df['ACN_P&O'] = pd.to_numeric(sem_6_2015_df["ACN_P&O"], errors='coerce')

sem_6_2015_df['SPCC'] = pd.to_numeric(sem_6_2015_df["SPCC"], errors='coerce')
sem_6_2015_df['SPCC_TW'] = pd.to_numeric(sem_6_2015_df["SPCC_TW"], errors='coerce')
sem_6_2015_df['SPCC_P&O'] = pd.to_numeric(sem_6_2015_df["SPCC_P&O"], errors='coerce')

sem_6_2015_df['OOSE'] = pd.to_numeric(sem_6_2015_df["OOSE"], errors='coerce')
sem_6_2015_df['OOSE_TW'] = pd.to_numeric(sem_6_2015_df["OOSE_TW"], errors='coerce')
sem_6_2015_df['OOSE_P&O'] = pd.to_numeric(sem_6_2015_df["OOSE_P&O"], errors='coerce')

sem_6_2015_df['AMP'] = pd.to_numeric(sem_6_2015_df["AMP"], errors='coerce')
sem_6_2015_df['AMP_TW'] = pd.to_numeric(sem_6_2015_df["AMP_TW"], errors='coerce')
sem_6_2015_df['AMP_P&O'] = pd.to_numeric(sem_6_2015_df["AMP_P&O"], errors='coerce')

sem_6_2015_df['DWM'] = pd.to_numeric(sem_6_2015_df["DWM"], errors='coerce')
sem_6_2015_df['DWM_TW'] = pd.to_numeric(sem_6_2015_df["DWM_TW"], errors='coerce')
sem_6_2015_df['DWM_P&O'] = pd.to_numeric(sem_6_2015_df["DWM_P&O"], errors='coerce')

sem_6_2015_df['SEMR'] = pd.to_numeric(sem_6_2015_df["SEMR"], errors='coerce')
sem_6_2015_df['SEMR_P&O']= pd.to_numeric(sem_6_2015_df["SEMR_P&O"], errors='coerce')

sem_6_2015_df['TOT VI'] = pd.to_numeric(sem_6_2015_df["TOT VI"], errors='coerce')
sem_6_2015_df['TOT V'] = pd.to_numeric(sem_6_2015_df["TOT V"], errors='coerce')
sem_6_2015_df['GNT'] = pd.to_numeric(sem_6_2015_df["GNT"], errors='coerce')

In [17]:
sem_6_2015_df.describe()

,ACN,ACN_TW,ACN_P&O,SPCC,SPCC_TW,SPCC_P&O,OOSE,OOSE_TW,OOSE_P&O,AMP,AMP_TW,AMP_P&O,DWM,DWM_TW,DWM_P&O,SEMR,SEMR_P&O,TOT VI,TOT V,GNT
count,158.000000,161.000000,161.000000,156.000000,161.000000,161.000000,158.000000,161.000000,161.000000,156.000000,161.000000,161.000000,158.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,52.056962,21.583851,43.496894,59.993590,21.596273,21.720497,53.772152,21.267081,43.366460,52.698718,20.664596,20.496894,54.341772,21.142857,21.018634,20.795031,20.397516,563.925466,480.670807,1044.596273
std,13.262775,1.602962,2.932840,13.316735,1.744201,1.601605,11.252119,1.977238,3.077518,12.054939,2.055310,2.064958,11.948814,1.592393,1.660091,1.250590,1.467479,75.344837,164.802259,228.959177
min,2.000000,14.000000,34.000000,2.000000,13.000000,13.000000,0.000000,14.000000,34.000000,4.000000,14.000000,14.000000,4.000000,18.000000,16.000000,18.000000,17.000000,253.000000,0.000000,253.000000
25%,44.000000,20.000000,42.000000,51.750000,21.000000,21.000000,48.000000,20.000000,41.000000,45.000000,19.000000,19.000000,44.000000,20.000000,20.000000,20.000000,19.000000,535.000000,493.000000,1031.000000
50%,54.000000,22.000000,44.000000,60.000000,22.000000,22.000000,55.000000,22.000000,44.000000,53.000000,21.000000,21.000000,56.000000,21.000000,21.000000,21.000000,20.000000,580.000000,525.000000,1104.000000
75%,61.750000,23.000000,46.000000,70.000000,23.000000,23.000000,61.000000,23.000000,46.000000,61.000000,22.000000,22.000000,64.000000,22.000000,22.000000,22.000000,21.000000,615.000000,554.000000,1171.000000
max,75.000000,24.000000,48.000000,85.000000,24.000000,24.000000,77.000000,24.000000,48.000000,84.000000,24.000000,24.000000,80.000000,24.000000,24.000000,23.000000,24.000000,679.000000,638.000000,1289.000000

In [18]:
writer = pd.ExcelWriter('Sem-6_2015_Passout_cleaned.xlsx')

In [19]:
sem_6_2015_df.to_excel(writer,"Sem-6_2015_Passout_cleaned")
writer.save()