In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
% matplotlib inline

In [2]:
path = "../../Data/Exam Data/2015/CMPN SEM-IV_2013_june.xlsx"

In [3]:
sem_4_2015_df = pd.read_excel(path)

In [4]:
sem_4_2015_df

,EXAM SEAT NO.,NAME OF CANDIDATE,AM IV,Unnamed: 3,Unnamed: 4,Unnamed: 5,ADC,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,TOT IV,TOT III,GNT,REMARK,CLASS,Unnamed: 39
NaN,NaN,NaN,TH,NaN,TW,NaN,TH,NaN,TW,NaN,...,TW,NaN,P,NaN,850,850,1700,NaN,NaN,NaN
NaN,NaN,MAX,100,NaN,25,NaN,100,NaN,25,NaN,...,25,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,MIN,40,NaN,10,NaN,40,NaN,10,NaN,...,10,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,134201.0,AMIN RISHITA VIJAYKUMAR,40,NaN,18,NaN,40,NaN,22,NaN,...,22,NaN,16,NaN,442,0,442,PASS,RS 3,Four Hundred Forty Two
NaN,134202.0,AMRE PRITAM ANILKUMAR,64,NaN,20,NaN,69,NaN,23,NaN,...,23,NaN,19,NaN,596,566+,1162,PASS,I,One Thousand One Hundred Sixty Two
NaN,134203.0,ANSAN SUNNY SALAMA,42,E,16,E,40,E,19,E,...,19,E,17,E,417,0,417,FAIL,--,Four Hundred Seventeen
NaN,134204.0,ASRANI BHARTI LACHMAN,52,NaN,20,NaN,74,NaN,21,NaN,...,21,NaN,16,NaN,523,529+,1052,PASS,I,One Thousand Fifty Two
NaN,134205.0,BADE AMIT KERAMBA,40,NaN,18,NaN,50,NaN,17,NaN,...,19,NaN,17,NaN,437*,453x,890,PASS,P,Eight Hundred Ninety
NaN,134206.0,BAGWE KARAN VINAY,65,NaN,17,NaN,63,NaN,20,NaN,...,18,NaN,16,NaN,563,553+,1116,PASS,I,One Thousand One Hundred Sixteen
NaN,134207.0,BANDIVADEKAR RUTALI DILIP,61,NaN,22,NaN,70,NaN,21,NaN,...,21,NaN,18,NaN,597,616+,1213,PASS,I,One Thousand Two Hundred Thirteen
NaN,134208.0,BARBHAYA RISHI DIVYESH,20,F,16,E,59,E,19,E,...,18,E,17,E,486,469x,955,FAIL,--,Nine Hundred Fifty Five
NaN,134209.0,BELWALKAR MANALI CHANDRAKANT,63,NaN,23,NaN,68,NaN,23,NaN,...,23,NaN,16,NaN,537,500*+,1037,PASS,I,One Thousand Thirty Seven
NaN,134210.0,BHAGAT DOLLY DEEPAK,40,NaN,20,NaN,50,NaN,23,NaN,...,22,NaN,20,NaN,476,510x,986,PASS,P,Nine Hundred Eighty Six
NaN,134211.0,BHALERAO DEVENDRA SURESH,17,F,16,E,52,E,18,E,...,20,E,19,E,411,420x,831,FAIL,--,Eight Hundred Thirty One
NaN,134212.0,BHOITE KISHORI PRABHAKAR,40,E,24,E,40,E,21,E,...,23,E,20,E,403,479*+,882,FAIL,--,Eight Hundred Eighty Two
NaN,134213.0,BORSE KIRAN HILAL,40,E,16,E,46,E,19,E,...,19,E,17,E,411,460*+,871,FAIL,--,Eight Hundred Seventy One
NaN,134214.0,CHAUHAN ANJALI RAJU,7,F,13,E,12,F,19,E,...,20,E,18,E,361,0,361,FAIL,--,Three Hundred Sixty One
NaN,134215.0,CHAVAN GAURAV SHRIDHAR,40,NaN,23,NaN,63,NaN,20,NaN,...,19,NaN,16,NaN,504,524+,1028,PASS,I,One Thousand Twenty Eight
NaN,134216.0,CHAVAN KOMAL DATTATRAY,28,F,21,E,40,E,21,E,...,21,E,19,E,428,486x,914,FAIL,--,Nine Hundred Fourteen
NaN,134217.0,CHAVAN SHASHANK GAJANAN,48,NaN,22,NaN,62,NaN,23,NaN,...,23,NaN,15,NaN,529,499+,1028#10,PASS,I,NaN
NaN,134218.0,CHAVHAN AMOL SUBHASH,29,F,17,E,40,E,23,E,...,23,E,18,E,420,456x,876,FAIL,--,Eight Hundred Seventy Six
NaN,134219.0,CHILE AKSHAY VISHWANATH,44,E,16,E,30,F,16,E,...,19,E,15,E,438,470x,908,FAIL,--,Nine Hundred Eight
NaN,134220.0,CHILKA PRIYANKA RAJENDRA,50,NaN,21,NaN,68,NaN,21,NaN,...,21,NaN,16,NaN,529,558+,1087,PASS,I,One Thousand Eighty Seven
NaN,134221.0,CHITRE ABHISHEK ANIL,AB,NaN,16,E,43,E,23,E,...,23,E,18,E,371,0,371,FAIL,--,Three Hundred Seventy One
NaN,134222.0,CHONKAR SHRIKAR RAVINDRA,23,F,17,E,55,E,23,E,...,23,E,23,E,478,0,478,FAIL,--,Four Hundred Seventy Eight
NaN,134223.0,DADAS JITESH TATYA,AB,NaN,15,E,40,E,19,E,...,16,E,17,E,290,0,290,FAIL,--,Two Hundred Ninety
NaN,134224.0,DALVI NILESHA NANDKISHOR,55,NaN,20,NaN,50,NaN,23,NaN,...,23,NaN,15,NaN,529,492*+,1021,PASS,I,One Thousand Twenty One
NaN,134225.0,DANDE AKASH NARAYAN,62,NaN,24,NaN,58,NaN,23,NaN,...,23,NaN,15,NaN,587,553+,1140#10,PASS,I,NaN
NaN,134226.0,DAVE RAJENDRA AJAY,24,F,19,E,79,E,18,E,...,22,E,19,E,527,498x,1025,FAIL,--,One Thousand Twenty Five
NaN,134227.0,DEEPALI GANPATI KHOT,40,NaN,21,NaN,77,NaN,21,NaN,...,23,NaN,22,NaN,572,634x,1206,PASS,P,One Thousand Two Hundred Six
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,134358.0,KATARIYA SURYAKANT PREMJIBHAI,44,NaN,20+,,45+,,20+,,...,20+,,16+,,432,503x,935,PASS,P,Nine Hundred Thirty Five
NaN,134359.0,KELUSKAR PRAVIN PURUSHOTTAM,40+,,20+,,28,F,20+,,...,21+,,16+,,437,0,437,FAIL,--,Four Hundred Thirty Seven
NaN,134360.0,KEWAT ATUL BHARATBHUSHAN,AB,NaN,21+,,AB,NaN,19+,,...,22+,,19+,,289,0,289,ABSENT,AB,Two Hundred Eighty Nine
NaN,134361.0,MADHWA TANUJ RADHEY SHYAM,21,F,13+,,5,F,15+,,...,20+,,15+,,316,0,316,FAIL,--,Three Hundred Sixteen
NaN,134362.0,OZA ADITYA SUNIL KUMAR,AB,NaN,12+,,43+,,15+,,...,19+,,12+,,361,0,361,FAIL,--,Three Hundred Sixty One
NaN,134363.0,PALEKAR AKSHAY ANIL,11,F,20+,,44,E,21+,,...,20+,,15+,,422,479x,901,FAIL,--,Nine Hundred One
NaN,134364.0,PARANDE MANDAR MANGESH,44+,,18+,,53,NaN,19+,,...,20+,,17+,,453,0,453,PASS,RS 3,Four Hundred Fifty Three
NaN,134365.0,PARKAR SIDDHANT RAJIV,40,NaN,23+,,47+,,19+,,...,20+,,16+,,447,478x,925,PASS,P,Nine Hundred Twenty Five
NaN,134366.0,PATEL JAY BIPIN,55+,,19+,,51,NaN,17+,,...,18+,,13+,,458,511x,969,PASS,P,Nine Hundred Sixty Nine
NaN,134367.0,PATIL GAURAV BHAURAO,43+,,19+,,30,F,17+,,...,18+,,14+,,425,0,425,FAIL,--,Four Hundred Twenty Five
NaN,134368.0,PATKAR DIPIKA SANTOSH,40,NaN,14+,,40+,,19+,,...,22+,,16+,,433,447x,880,PASS,P,Eight Hundred Eighty
NaN,134369.0,PATWARDHAN ANIKET ASHOK,41+,,19+,,40,E,19+,,...,18+,,17+,,400,0,400,FAIL,--,Four Hundred
NaN,134370.0,PEVEKAR NEHA BALKRISHNA,47+,,19+,,46,NaN,20+,,...,20+,,16+,,462,454x,916,PASS,P,Nine Hundred Sixteen
NaN,134371.0,RANE YUGANDHARA CHANDRAMOHAN,45+,,19+,,50,NaN,21+,,...,21+,,15+,,482,499x,981,PASS,P,Nine Hundred Eighty One
NaN,134372.0,SAKHALE NIMESH HEMANT,8,F,18+,,40,E,19+,,...,20+,,18+,,398,0,398,FAIL,--,Three Hundred NinetyEight
NaN,134373.0,SATARDEKAR SIDDHESH NANDKUMAR,40+,,20+,,50+,,18+,,...,17+,,16+,,430,457x,887,PASS,P,Eight Hundred Eighty Seven
NaN,134374.0,SHARMA SHIVAM SUBHASH,40+,,18+,,45,NaN,21+,,...,20+,,14+,,414,475x,889,PASS,P,Eight Hundred Eighty Nine
NaN,134375.0,SHUKLA MANOJ SHOBHNATH,40+,,20+,,40,NaN,21+,,...,20+,,17+,,471,497x,968,PASS,P,Nine Hundred Sixty Eight
NaN,134376.0,SURYAWANSHI PRIYANKA MADHUKAR,40+,,19+,,33,F,19+,,...,20+,,16+,,411,0,411,FAIL,--,Four Hundred Eleven
NaN,134377.0,VISHWAKARMA PARSHURAM SHIVMURAT,AB,NaN,12+,,AB,NaN,17+,,...,15+,,11+,,225,0,225,ABSENT,AB,Two Hundred Twenty Five
NaN,134378.0,ADMANE PRADIP VIDNYANRAO,AB,NaN,19+,,49,E,18+,,...,19+,,18+,,388,0,388,FAIL,--,Three Hundred Eighty Eight
NaN,134379.0,DEORE SANKET GOVIND,12,F,20+,,40+,,19+,,...,20+,,16+,,401,0,401,FAIL,--,Four Hundred One
NaN,134380.0,KHOBRAGADE ASHISH MAHESH,26,F,18+,,53+,,22+,,...,19+,,15+,,454,0,454,FAIL,--,Four Hundred Fifty Four
NaN,134381.0,SIDHPURA CHIRAG VIJAY,12,F,17+,,43+,,17+,,...,14+,,13+,,449,0,449,FAIL,--,Four Hundred Forty Nine
NaN,134382.0,THAKKER PARTH JAYESH,0,F,14,E,40,E,23,E,...,19,E,19,E,361,0,361,FAIL,--,Three Hundred Sixty One
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Total No. of Students Appeared :,NaN,NaN,NaN,179,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Total No. of Students Passed :,NaN,NaN,NaN,98,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Overall Percentage of Passing :,NaN,NaN,NaN,0.547486,NaN

In [5]:
sem_4_2015_df.dropna(subset=['EXAM SEAT NO.'],inplace=True)

In [7]:
sem_4_2015_df.dropna(axis=0, how='all',inplace=True)

In [9]:
sem_4_2015_df.index = sem_4_2015_df['EXAM SEAT NO.']

In [11]:
sem_4_2015_df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 182 entries, 134201.0 to 134382.0
Data columns (total 40 columns):
EXAM SEAT NO.        182 non-null float64
NAME OF CANDIDATE    182 non-null object
AM IV                182 non-null object
Unnamed: 3           79 non-null object
Unnamed: 4           182 non-null object
Unnamed: 5           95 non-null object
ADC                  182 non-null object
Unnamed: 7           79 non-null object
Unnamed: 8           182 non-null object
Unnamed: 9           95 non-null object
DBMS                 182 non-null object
Unnamed: 11          90 non-null object
Unnamed: 12          182 non-null object
Unnamed: 13          95 non-null object
Unnamed: 14          182 non-null object
Unnamed: 15          95 non-null object
CG                   182 non-null object
Unnamed: 17          90 non-null object
Unnamed: 18          182 non-null object
Unnamed: 19          95 non-null object
Unnamed: 20          182 non-null object
Unnamed: 21          95 non-null object
AAD                  182 non-null object
Unnamed: 23          89 non-null object
Unnamed: 24          182 non-null object
Unnamed: 25          95 non-null object
Unnamed: 26          182 non-null object
Unnamed: 27          95 non-null object
OS                   182 non-null object
Unnamed: 29          88 non-null object
Unnamed: 30          182 non-null object
Unnamed: 31          95 non-null object
Unnamed: 32          182 non-null object
Unnamed: 33          95 non-null object
TOT IV               182 non-null object
TOT III              182 non-null object
GNT                  182 non-null object
REMARK               182 non-null object
CLASS                182 non-null object
Unnamed: 39          175 non-null object
dtypes: float64(1), object(39)
memory usage: 58.3+ KB

In [13]:
sem_4_2015_df.columns.values[[3,4,5,7,8,9]] = ['AMIV_Grade','AMIV_TW','AMIV_TW_Grade','ADC_Grade','ADC_TW','ADC_TW_Grade']
sem_4_2015_df.columns.values[[11,12,13,14,15]] = ['DBMS_Grade','DBMS_TW','DBMS_TW_Grade','DBMS_Practical','DBMS_Practical_Grade']
sem_4_2015_df.columns.values[[17,18,19,20,21]] = ['CG_Grade','CG_TW','CG_TW_Grade','CG_Practical','CG_Practical_Grade']
sem_4_2015_df.columns.values[[23,24,25,26,27]] = ['AAD_Grade','AAD_TW','AAD_TW_Grade','AAD_Practical','AAD_Practical_Grade']
sem_4_2015_df.columns.values[[29,30,31,32,33]] = ['OS_Grade','OS_TW','OS_TW_Grade','OS_Practical','OS_Practical_Grade']

In [15]:
sem_4_2015_df = sem_4_2015_df.rename_axis(lambda x: x, 1, True)

In [16]:
sem_4_2015_df

,EXAM SEAT NO.,NAME OF CANDIDATE,AM IV,AMIV_Grade,AMIV_TW,AMIV_TW_Grade,ADC,ADC_Grade,ADC_TW,ADC_TW_Grade,...,OS_TW,OS_TW_Grade,OS_Practical,OS_Practical_Grade,TOT IV,TOT III,GNT,REMARK,CLASS,Unnamed: 39
EXAM SEAT NO.,,,,,,,,,,,,,,,,,,,,,
134201.0,134201.0,AMIN RISHITA VIJAYKUMAR,40,NaN,18,NaN,40,NaN,22,NaN,...,22,NaN,16,NaN,442,0,442,PASS,RS 3,Four Hundred Forty Two
134202.0,134202.0,AMRE PRITAM ANILKUMAR,64,NaN,20,NaN,69,NaN,23,NaN,...,23,NaN,19,NaN,596,566+,1162,PASS,I,One Thousand One Hundred Sixty Two
134203.0,134203.0,ANSAN SUNNY SALAMA,42,E,16,E,40,E,19,E,...,19,E,17,E,417,0,417,FAIL,--,Four Hundred Seventeen
134204.0,134204.0,ASRANI BHARTI LACHMAN,52,NaN,20,NaN,74,NaN,21,NaN,...,21,NaN,16,NaN,523,529+,1052,PASS,I,One Thousand Fifty Two
134205.0,134205.0,BADE AMIT KERAMBA,40,NaN,18,NaN,50,NaN,17,NaN,...,19,NaN,17,NaN,437*,453x,890,PASS,P,Eight Hundred Ninety
134206.0,134206.0,BAGWE KARAN VINAY,65,NaN,17,NaN,63,NaN,20,NaN,...,18,NaN,16,NaN,563,553+,1116,PASS,I,One Thousand One Hundred Sixteen
134207.0,134207.0,BANDIVADEKAR RUTALI DILIP,61,NaN,22,NaN,70,NaN,21,NaN,...,21,NaN,18,NaN,597,616+,1213,PASS,I,One Thousand Two Hundred Thirteen
134208.0,134208.0,BARBHAYA RISHI DIVYESH,20,F,16,E,59,E,19,E,...,18,E,17,E,486,469x,955,FAIL,--,Nine Hundred Fifty Five
134209.0,134209.0,BELWALKAR MANALI CHANDRAKANT,63,NaN,23,NaN,68,NaN,23,NaN,...,23,NaN,16,NaN,537,500*+,1037,PASS,I,One Thousand Thirty Seven
134210.0,134210.0,BHAGAT DOLLY DEEPAK,40,NaN,20,NaN,50,NaN,23,NaN,...,22,NaN,20,NaN,476,510x,986,PASS,P,Nine Hundred Eighty Six
134211.0,134211.0,BHALERAO DEVENDRA SURESH,17,F,16,E,52,E,18,E,...,20,E,19,E,411,420x,831,FAIL,--,Eight Hundred Thirty One
134212.0,134212.0,BHOITE KISHORI PRABHAKAR,40,E,24,E,40,E,21,E,...,23,E,20,E,403,479*+,882,FAIL,--,Eight Hundred Eighty Two
134213.0,134213.0,BORSE KIRAN HILAL,40,E,16,E,46,E,19,E,...,19,E,17,E,411,460*+,871,FAIL,--,Eight Hundred Seventy One
134214.0,134214.0,CHAUHAN ANJALI RAJU,7,F,13,E,12,F,19,E,...,20,E,18,E,361,0,361,FAIL,--,Three Hundred Sixty One
134215.0,134215.0,CHAVAN GAURAV SHRIDHAR,40,NaN,23,NaN,63,NaN,20,NaN,...,19,NaN,16,NaN,504,524+,1028,PASS,I,One Thousand Twenty Eight
134216.0,134216.0,CHAVAN KOMAL DATTATRAY,28,F,21,E,40,E,21,E,...,21,E,19,E,428,486x,914,FAIL,--,Nine Hundred Fourteen
134217.0,134217.0,CHAVAN SHASHANK GAJANAN,48,NaN,22,NaN,62,NaN,23,NaN,...,23,NaN,15,NaN,529,499+,1028#10,PASS,I,NaN
134218.0,134218.0,CHAVHAN AMOL SUBHASH,29,F,17,E,40,E,23,E,...,23,E,18,E,420,456x,876,FAIL,--,Eight Hundred Seventy Six
134219.0,134219.0,CHILE AKSHAY VISHWANATH,44,E,16,E,30,F,16,E,...,19,E,15,E,438,470x,908,FAIL,--,Nine Hundred Eight
134220.0,134220.0,CHILKA PRIYANKA RAJENDRA,50,NaN,21,NaN,68,NaN,21,NaN,...,21,NaN,16,NaN,529,558+,1087,PASS,I,One Thousand Eighty Seven
134221.0,134221.0,CHITRE ABHISHEK ANIL,AB,NaN,16,E,43,E,23,E,...,23,E,18,E,371,0,371,FAIL,--,Three Hundred Seventy One
134222.0,134222.0,CHONKAR SHRIKAR RAVINDRA,23,F,17,E,55,E,23,E,...,23,E,23,E,478,0,478,FAIL,--,Four Hundred Seventy Eight
134223.0,134223.0,DADAS JITESH TATYA,AB,NaN,15,E,40,E,19,E,...,16,E,17,E,290,0,290,FAIL,--,Two Hundred Ninety
134224.0,134224.0,DALVI NILESHA NANDKISHOR,55,NaN,20,NaN,50,NaN,23,NaN,...,23,NaN,15,NaN,529,492*+,1021,PASS,I,One Thousand Twenty One
134225.0,134225.0,DANDE AKASH NARAYAN,62,NaN,24,NaN,58,NaN,23,NaN,...,23,NaN,15,NaN,587,553+,1140#10,PASS,I,NaN
134226.0,134226.0,DAVE RAJENDRA AJAY,24,F,19,E,79,E,18,E,...,22,E,19,E,527,498x,1025,FAIL,--,One Thousand Twenty Five
134227.0,134227.0,DEEPALI GANPATI KHOT,40,NaN,21,NaN,77,NaN,21,NaN,...,23,NaN,22,NaN,572,634x,1206,PASS,P,One Thousand Two Hundred Six
134228.0,134228.0,DESAI CHINMAY PRAKASH,15,F,16,E,55,E,20,E,...,23,E,16,E,375,0,375,FAIL,--,Three Hundred Seventy Five
134229.0,134229.0,DEVLEKAR RAHUL PRAKASH,41,NaN,19,NaN,58,NaN,23,NaN,...,23,NaN,18,NaN,512,501x,512#10,PASS,P,NaN
134230.0,134230.0,DHULE AMEY YASHWANT,44,NaN,17,NaN,60,NaN,23,NaN,...,23,NaN,17,NaN,519,475+,994,PASS,II,Nine Hundred NinetyFour
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134353.0,134353.0,DESAI MIHIR BHUPESH,5,F,18+,,3,F,21+,,...,20+,,18+,,306,0,306,FAIL,--,Three Hundred Six
134354.0,134354.0,GHUMAN RAJNEET SINGH IQBAL SINGH,17,F,15+,,41+,,18+,,...,21+,,19+,,397,0,397,FAIL,--,Three Hundred NinetySeven
134355.0,134355.0,KADIWALA REHAN KARIM,55+,,20+,,49,NaN,17+,,...,20+,,19+,,475,443x,918,PASS,P,Nine Hundred Eighteen
134356.0,134356.0,KAMBLE ABHISHEK DINKAR,4,F,20+,,30,F,17+,,...,18+,,17+,,314,0,314,FAIL,--,Three Hundred Fourteen
134357.0,134357.0,KATARE SUNITA DATTU,40,NaN,20+,,40+,,20+,,...,21+,,18+,,455,483x,938,PASS,P,Nine Hundred Thirty Eight
134358.0,134358.0,KATARIYA SURYAKANT PREMJIBHAI,44,NaN,20+,,45+,,20+,,...,20+,,16+,,432,503x,935,PASS,P,Nine Hundred Thirty Five
134359.0,134359.0,KELUSKAR PRAVIN PURUSHOTTAM,40+,,20+,,28,F,20+,,...,21+,,16+,,437,0,437,FAIL,--,Four Hundred Thirty Seven
134360.0,134360.0,KEWAT ATUL BHARATBHUSHAN,AB,NaN,21+,,AB,NaN,19+,,...,22+,,19+,,289,0,289,ABSENT,AB,Two Hundred Eighty Nine
134361.0,134361.0,MADHWA TANUJ RADHEY SHYAM,21,F,13+,,5,F,15+,,...,20+,,15+,,316,0,316,FAIL,--,Three Hundred Sixteen
134362.0,134362.0,OZA ADITYA SUNIL KUMAR,AB,NaN,12+,,43+,,15+,,...,19+,,12+,,361,0,361,FAIL,--,Three Hundred Sixty One
134363.0,134363.0,PALEKAR AKSHAY ANIL,11,F,20+,,44,E,21+,,...,20+,,15+,,422,479x,901,FAIL,--,Nine Hundred One
134364.0,134364.0,PARANDE MANDAR MANGESH,44+,,18+,,53,NaN,19+,,...,20+,,17+,,453,0,453,PASS,RS 3,Four Hundred Fifty Three
134365.0,134365.0,PARKAR SIDDHANT RAJIV,40,NaN,23+,,47+,,19+,,...,20+,,16+,,447,478x,925,PASS,P,Nine Hundred Twenty Five
134366.0,134366.0,PATEL JAY BIPIN,55+,,19+,,51,NaN,17+,,...,18+,,13+,,458,511x,969,PASS,P,Nine Hundred Sixty Nine
134367.0,134367.0,PATIL GAURAV BHAURAO,43+,,19+,,30,F,17+,,...,18+,,14+,,425,0,425,FAIL,--,Four Hundred Twenty Five
134368.0,134368.0,PATKAR DIPIKA SANTOSH,40,NaN,14+,,40+,,19+,,...,22+,,16+,,433,447x,880,PASS,P,Eight Hundred Eighty
134369.0,134369.0,PATWARDHAN ANIKET ASHOK,41+,,19+,,40,E,19+,,...,18+,,17+,,400,0,400,FAIL,--,Four Hundred
134370.0,134370.0,PEVEKAR NEHA BALKRISHNA,47+,,19+,,46,NaN,20+,,...,20+,,16+,,462,454x,916,PASS,P,Nine Hundred Sixteen
134371.0,134371.0,RANE YUGANDHARA CHANDRAMOHAN,45+,,19+,,50,NaN,21+,,...,21+,,15+,,482,499x,981,PASS,P,Nine Hundred Eighty One
134372.0,134372.0,SAKHALE NIMESH HEMANT,8,F,18+,,40,E,19+,,...,20+,,18+,,398,0,398,FAIL,--,Three Hundred NinetyEight
134373.0,134373.0,SATARDEKAR SIDDHESH NANDKUMAR,40+,,20+,,50+,,18+,,...,17+,,16+,,430,457x,887,PASS,P,Eight Hundred Eighty Seven
134374.0,134374.0,SHARMA SHIVAM SUBHASH,40+,,18+,,45,NaN,21+,,...,20+,,14+,,414,475x,889,PASS,P,Eight Hundred Eighty Nine
134375.0,134375.0,SHUKLA MANOJ SHOBHNATH,40+,,20+,,40,NaN,21+,,...,20+,,17+,,471,497x,968,PASS,P,Nine Hundred Sixty Eight
134376.0,134376.0,SURYAWANSHI PRIYANKA MADHUKAR,40+,,19+,,33,F,19+,,...,20+,,16+,,411,0,411,FAIL,--,Four Hundred Eleven
134377.0,134377.0,VISHWAKARMA PARSHURAM SHIVMURAT,AB,NaN,12+,,AB,NaN,17+,,...,15+,,11+,,225,0,225,ABSENT,AB,Two Hundred Twenty Five
134378.0,134378.0,ADMANE PRADIP VIDNYANRAO,AB,NaN,19+,,49,E,18+,,...,19+,,18+,,388,0,388,FAIL,--,Three Hundred Eighty Eight
134379.0,134379.0,DEORE SANKET GOVIND,12,F,20+,,40+,,19+,,...,20+,,16+,,401,0,401,FAIL,--,Four Hundred One
134380.0,134380.0,KHOBRAGADE ASHISH MAHESH,26,F,18+,,53+,,22+,,...,19+,,15+,,454,0,454,FAIL,--,Four Hundred Fifty Four
134381.0,134381.0,SIDHPURA CHIRAG VIJAY,12,F,17+,,43+,,17+,,...,14+,,13+,,449,0,449,FAIL,--,Four Hundred Forty Nine
134382.0,134382.0,THAKKER PARTH JAYESH,0,F,14,E,40,E,23,E,...,19,E,19,E,361,0,361,FAIL,--,Three Hundred Sixty One